config/routes.rb
Rails.application.routes.draw do
  devise_for(:users, controllers: { registrations: "registrations" })

  resources(:users, only: [:show])
  resources(:events) do 
    member do
      # https://www.rubydoc.info/docs/rails/4.1.7/ActionDispatch/Routing/Mapper/Resources
      post("attendance", to: "attendances#enroll")
      delete("attendance", to: "attendances#unenroll")
    end
  end

  root("events#index")

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to(:creator, class_name: "User")
  has_and_belongs_to_many(:attendees,
                          join_table: "attended_events",
                          foreign_key: "attended_event_id",
                          association_foreign_key: "attendee_id",
                          class_name: "User")
  before_destroy { attendees.clear }

  validates(:title, presence: true)
  validates(:description, presence: true)
  validates(:date, presence: true)
  validates(:location, presence: true)

  scope(:upcoming, ->() {
    today = DateTime.now
    today_zero = DateTime.new(today.year, today.month, today.day, 0, 0, 0)
    where("date >= ?", today_zero)
  })

  scope(:past, ->() {
    today = DateTime.now
    today_zero = DateTime.new(today.year, today.month, today.day, 0, 0, 0)
    where("date < ?", today_zero)
  })
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many(:events, foreign_key: "creator_id", dependent: :destroy)
  has_and_belongs_to_many(:attended_events,
                          join_table: "attended_events",
                          foreign_key: "attendee_id",
                          association_foreign_key: "attended_event_id",
                          class_name: "Event")

  validates(:username, presence: true)
  validates(:email, presence: true)
  validates(:password, presence: true, length: { minimum: 6 })

  def enrolled_to?(event)
    event.attendees.where(id: self).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def enroll
    event = Event.find(params[:id])
    current_user.attended_events << event

    redirect_to(event_path(event))
  end

  def unenroll
    event = Event.find(params[:id])
    current_user.attended_events.delete(event)

    redirect_to(event_path(event))
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    # today = today_zeroed
    # @upcoming_events = Event.where("date >= ?", today)
    # @past_events = Event.where("date < ?", today)
    @upcoming_events = Event.upcoming
    @past_events = Event.past
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
  end

  def new
    @event = current_user.events.build
    # @event.date = Time.now
    # TODO: Handle time zones
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:notice] = "Event successfully created"
      redirect_to(root_path)
    else
      flash[:alert] = "Failed to create event"
      render(:new, status: :unprocessable_entity)
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:notice] = "Event successfully updated"
      redirect_to(root_path)
    else
      flash[:alert] = "Failed to update event"
      render(:new, status: :unprocessable_entity)
    end
  end

  def destroy
    @event = Event.find(params[:id])

    if @event.creator == current_user
      @event.destroy
      flash[:notice] = "Event successfully deleted"
    else
      flash[:alert] = "Cannot delete other's user events"
    end

    redirect_to(root_path)
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :location)
  end

  # def today_zeroed
  #   today = DateTime.now
  #   today_zero = DateTime.new(today.year, today.month, today.day, 0, 0, 0)
  #   return today_zero
  # end
end

app/controllers/registations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    # today = today_zeroed
    # @my_events = current_user.events
    # @attending_events = current_user.attended_events.where("date >= ?", today)
    # @past_attended_events = current_user.attended_events.where("date < ?", today)
    @my_events = current_user.events
    @attending_events = current_user.attended_events.upcoming
    @past_attended_events = current_user.attended_events.past
  end

  # private

  # def today_zeroed
  #   today = DateTime.now
  #   today_zero = DateTime.new(today.year, today.month, today.day, 0, 0, 0)
  #   return today_zero
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<article class="event-card">
<a href="<%= event_path(event) %>" 
   class="event-card-clickable event-card-container">
    <h3 class="title"><%= event.title %></h3>

    <%# https://apidock.com/ruby/DateTime/strftime %>
    <div>
        <i class="fa-solid fa-calendar-days"></i>
        <small class="date"><%= event.date.strftime("%a, %b %d, %Y %I:%M %p") %> UTC<%= event.date.strftime("%:z") %></small>
    </div>
    
    <div>
        <i class="fa-solid fa-location-dot"></i>
        <small class="location"><%= event.location %></small>
    </div>

    <div>
        <i class="fa-regular fa-user"></i>
        <small class="author">By <strong><%= event.creator.username %></strong></small>
    </div>
</a>
</article>

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
    <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
    </div>

        <div class="field">
            <%= f.label :date %>
            <div><%= f.datetime_select :date %></div>
        </div>

        <div class="field">
            <%= f.label :location %><br />
            <%= f.text_field :location %>
        </div>

    <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description, rows: "10" %>
    </div>

    <div class="actions">
        <%= f.submit "Save", class: "btn-primary" %>
    </div>
<% end %>

app/views/events/edit.html.erb
<section class="main-container">
    <div></div>

    <div class="auth-panel box">
        <h2>Edit Event</h2>

        <%= render("form", event: @event) %>
    </div>

    <div></div>
</section>

app/views/events/index.html.erb
<main>
    <h2 class="h2">Upcoming Events</h2>
    
    <section class="events-container">
        <%= render @upcoming_events %>
    </section>

    <h2 class="h2">Past Events</h2>

        <section class="events-container">
        <%= render @past_events %>
    </section>
</main>

app/views/events/new.html.erb
<main class="main-container">
    <div></div>

    <section>
        <h1>New Event</h1>
        <span>Creator: <strong><%= @event.creator.username %></strong></span>
    </section>

    <div></div>
</main>

app/views/events/show.html.erb
<section class="main-container">
    <div></div>

    <article class="event">
        <h1 class="title"><%= @event.title %></h1>

        <div class="description">
            <h2 class="medium-title">About this event</h2>
            <p class="wrap-lines"><%= @event.description %></p>
        </div>

        <div class="side">
            <div class="tag">
                <i class="fa-regular fa-user"></i>
                <small class="author">Created by <strong><%= @event.creator.username %></strong></small>
            </div>
            <%# https://apidock.com/ruby/DateTime/strftime %>
    
            <div>
                <div class="tag">
                    <i class="fa-solid fa-calendar-days"></i>
                    <h3 class="small-title">Time and Date:</h3>
                </div>
                <small class="date"><%= @event.date.strftime("%a, %b %d, %Y %I:%M %p") %> UTC<%= @event.date.strftime("%:z") %></small>
            </div>
            
            <div>
                <div class="tag">
                    <i class="fa-solid fa-location-dot"></i>
                    <h3 class="small-title">Location:</h3>
                </div>
                <small class="location"><%= @event.location %></small>
            </div>

            <% if @event.creator != current_user %>
                <% if !current_user.nil? && current_user.enrolled_to?(@event) %>
                    <%= button_to("Unenroll", attendance_event_path(@event), class: "btn-outline-alert size-fill", method: :delete) %>
                <% else %>
                    <%# turbo: false in order to fix 
                        Processing by Devise::SessionsController#new as TURBO_STREAM
                        Completed 406 Not Acceptable error %>
                    <%= button_to("Enroll Now", attendance_event_path(@event), class: "link btn-outline-primary size-fill", form: { data: { turbo: false } }) %>
                <% end %>
            <% else %>
                    <%= button_to("Edit", edit_event_path(@event), class: "link btn-outline-primary size-fill", method: :get) %>
                    <%= button_to("Delete Event", event_path(@event), class: "btn-outline-alert size-fill", method: :delete,
                                  form: { data: { turbo_confirm: "Are you sure you want to delete this event? This cannot be undone" } }) %>
            <% end %>
        </div>

        <div class="attendees">
            <h2 class="medium-title">Who is attending?</h2>

            <div class="list">           
                <% @attendees.each do |attendee| %>
                    <small><%= attendee.username %></small>
                <% end %>
            </div>
        </div>
    </article>

    <div></div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/7dd9e33801.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" %> 
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="notifications">
      <% if flash[:notice] %>
        <div class="notification notice">
          <p class="msg"><%= notice %></p>
          <span class="close-btn"><i class="fa-solid fa-xmark"></i></span>
        </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="notification alert">
          <p class="msg"><%= alert %></p>
          <span class="close-btn"><i class="fa-solid fa-xmark"></i></span>
        </div>
      <% end %>
    </div>

    <header>
      <nav class="navbar">
        <div class="navbar-branding">
          <%= link_to("Private Events", root_path, class: "navbar-brand") %>
        </div>
        
        <ul class="navbar-items">
          <li class="nav-item">
              <%= link_to("Create Event", new_event_path, class: "link") %>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to(current_user.username, user_path(current_user), class: "link btn-outline-primary") %>
            </li>
            <li class="nav-item">
              <%= link_to("Log Out", destroy_user_session_path, class: "link",
                          data: { turbo_method: :delete }) %>
            </li>
          <% else %>
              <li class="nav-item">
                <%= link_to("Sign In", new_user_session_path, class: "link btn-outline-primary") %>
              </li>
              <li class="nav-item">
                <%= link_to("Sign Up", new_user_registration_path, class: "link btn-primary") %>
              </li>
          <% end %>
        </ul>

        <div class="navbar-burger">
          <i class="fa-solid fa-bars navbar-burger-item"></i>
        </div>
      </nav>

      <section class="burger-menu hidden">
        <div class="burger-items">
              <%= link_to("Create Event", new_event_path, class: "link burger-item") %>
          <% if user_signed_in? %>
              <%= link_to(current_user.username, user_path(current_user), class: "link burger-item") %>
              <%= link_to("Log Out", destroy_user_session_path, class: "link burger-item",
                          data: { turbo_method: :delete }) %>
          <% else %>
                <%= link_to("Sign In", new_user_session_path, class: "link burger-item") %>
                <%= link_to("Sign Up", new_user_registration_path, class: "link burger-item") %>
          <% end %>
        </div>
      </section>
    </header>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<main>
    <div class="flex-row flex-align-baseline">
        <h1 class="h2">Hi, <%= current_user.username %></h1>
        <%= link_to("Edit User", edit_user_registration_path, class: "link") %>
    </div>

    <h2 class="h2">My events</h2>
    
    <section class="events-container">
        <%= render @my_events %>
    </section>

    <h2 class="h2">Events I'm attending</h2>

    <section class="events-container">
        <%= render @attending_events %>
    </section>

    <h2 class="h2">Events I attended in the past</h2>

    <section class="events-container">
        <%= render @past_attended_events %>
    </section>
</main>